#!/bin/bash -eu
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2023  Alexey Gladkov <gladkov.alexey@gmail.com>

IMAGE_PATCHES="${IMAGE_PATCHES:?IMAGE_PATCHES required}"

. "$HOMEDIR"/env
. "$TOOLSDIR"/sh-functions

tag="$PROG"

! podman image exists "$IMAGE_SYSIMAGE:$tag" ||
	exit 0

podman image exists "$IMAGE_SYSIMAGE:latest" ||
	fatal "image \`$IMAGE_SYSIMAGE:latest' not found"

mkdir -p -- "$HOSTDIR"/patches.d
{
	printf 'FROM %s\n' "$IMAGE_SYSIMAGE:latest"
	for f in "$IMAGE_PATCHES"/*.patch; do
		cp -f -- "$f" "$HOSTDIR"/patches.d/
		printf 'RUN patch -p1 --merge < "/.host/patches.d/%s"\n' "${f##*/}"
	done
} |
	podman image build --squash --force-rm \
		-v "$HOSTDIR":/.host:z \
		-t "$IMAGE_SYSIMAGE:$tag" -f-

podman image tag "$IMAGE_SYSIMAGE:$tag" "$IMAGE_SYSIMAGE:latest"

find "$HOSTDIR" -mindepth 1 -maxdepth 1 -exec rm -rf -- '{}' '+'
