#!/bin/bash -eu

IMAGE_PATCHES="${IMAGE_PATCHES:?IMAGE_PATCHES required}"

. "$HOMEDIR"/env
. "$TOOLSDIR"/sh-functions

tag="$PROG"

! podman image exists "$IMAGE_SYSIMAGE:$tag" ||
	exit 0

podman image exists "$IMAGE_SYSIMAGE:latest" ||
	fatal "image \`$IMAGE_SYSIMAGE:latest' not found"

mkdir -p -- "$HOSTDIR"/patches.d
cp $verbose -af -- "$IMAGE_PATCHES"/*.patch "$HOSTDIR"/patches.d/

mkexec "$HOSTDIR/$PROG.chrooted" <<-EOF
#!/bin/sh -eu
for f in /.host/patches.d/*.patch; do
	[ -z "$verbose" ] || echo "$PROG: applying \$f ..."
	patch -p1 --merge < "\$f"
done
EOF

podman image build \
        -v "$HOSTDIR":/.host:z \
        -t "$IMAGE_SYSIMAGE:$tag" \
        -f - <<-EOF
FROM $IMAGE_SYSIMAGE:latest
RUN /.host/$PROG.chrooted
EOF

podman image tag "$IMAGE_SYSIMAGE:$tag" "$IMAGE_SYSIMAGE:latest"
