#!/bin/bash -efu

. "$HOMEDIR"/env

SYSIMAGE_PACKAGES="${SYSIMAGE_PACKAGES:?SYSIMAGE_PACKAGES variable required}"

if ! podman image exists "$IMAGE_SYSIMAGE:latest"; then
	for n in $SYSIMAGE_PACKAGES; do
		[ -f "$n" ] &&
			cat "$n" ||
			printf '%s\n' "$n"
	done > "$HOSTDIR"/packages

	prepare-chrooted "build-image"
	podman container run -v "$HOSTDIR":/.host:z "$IMAGE_BASEIMAGE"

	podman image import "$HOSTDIR/image.tar" "$IMAGE_SYSIMAGE:latest"
fi

exit
