#!/bin/bash -efu

. "$HOMEDIR"/env

! podman image exists "$IMAGE_BASEIMAGE:latest" ||
	exit 0

podman image build --squash --force-rm=true \
	-v "$HOSTDIR":/.host:z \
	-t "$IMAGE_BASEIMAGE:latest" \
	-f "$VENDORDIR/$VENDOR/Dockerfile.baseimage"
