#!/bin/bash -efu

. "$HOMEDIR"/env

if ! podman image exists "$IMAGE_BASEIMAGE"; then
	podman image build --pull --squash --force-rm=true \
		-v "$HOSTDIR":/.host:z \
		-t "$IMAGE_BASEIMAGE" \
		-f "$VENDORDIR/$VENDOR/Dockerfile.baseimage"
fi

exit
