#!/bin/bash -efu
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2023  Alexey Gladkov <gladkov.alexey@gmail.com>

. "$HOMEDIR"/env
. "$TOOLSDIR"/sh-functions

! podman image exists "$IMAGE_INSTRUMENTAL:latest" ||
	exit 0

set --

[ -z "${INSTRUMENTAL_FILES-}" ] ||
	set -- "$@" -v "$INSTRUMENTAL_FILES:/.host/files:z"

podman image build --squash --force-rm "${podman_common_volumes[@]}" "$@" \
	--build-arg verbose="$verbose" \
	--build-arg extra="${INSTRUMENTAL_PACKAGES-}" \
	--build-arg extra2="${INSTRUMENTAL_PACKAGES2-}" \
	-t "$IMAGE_INSTRUMENTAL:latest" \
	-f "$VENDORDIR/$VENDOR/Dockerfile.instrumental"

[ ! -d "$HOSTDIR"/.host/files ] ||
	rm -rf -- "$HOSTDIR":/.host/files
