#!/bin/bash -efu
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2023  Alexey Gladkov <gladkov.alexey@gmail.com>

. "$HOMEDIR"/env
. "$TOOLSDIR"/sh-functions

IMAGE_PACKAGES="${IMAGE_PACKAGES:?IMAGE_PACKAGES variable required}"

tag="${SYSIMAGE_TAG_PREFIX:+$SYSIMAGE_TAG_PREFIX-}$PROG"
latest="${SYSIMAGE_TAG_PREFIX:+$SYSIMAGE_TAG_PREFIX-}latest"

if podman image exists "$IMAGE_SYSIMAGE:$tag"; then
	podman image tag "$IMAGE_SYSIMAGE:$tag" "$IMAGE_SYSIMAGE:$latest"
	exit 0
fi

for n in ${IMAGE_ORDERED_PACKAGES-}; do
	if [ -f "$n" ]; then
		grep -v -e '^#' "$n" ||:
	else
		printf '%s\n' "$n"
	fi
done > "$HOSTDIR"/packages.ordered

for n in $IMAGE_PACKAGES; do
	if [ -f "$n" ]; then
		grep -v -e '^#' "$n" ||:
	else
		printf '%s\n' "$n"
	fi
done > "$HOSTDIR"/packages

copy_verndor_tools

create_vendor_helper "$PROG"

podman image build --squash --force-rm "${podman_common_volumes[@]}" \
	-t "$IMAGE_SYSIMAGE:$tag" -f- "$CURDIR" <<-EOF
FROM $IMAGE_SYSIMAGE:$latest
RUN /.host/$PROG.chrooted
EOF

podman image tag "$IMAGE_SYSIMAGE:$tag" "$IMAGE_SYSIMAGE:$latest"

find "$HOSTDIR" -mindepth 1 -maxdepth 1 -exec rm -rf -- '{}' '+'
