#!/bin/bash -efu
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2023  Alexey Gladkov <gladkov.alexey@gmail.com>

COPY_TREE="${COPY_TREE:?COPY_TREE required}"

. "$HOMEDIR"/env
. "$TOOLSDIR"/sh-functions

tag="$PROG"
latest="latest"

if podman image exists "$IMAGE_SYSIMAGE:$tag"; then
	podman image tag "$IMAGE_SYSIMAGE:$tag" "$IMAGE_SYSIMAGE:$latest"
	exit 0
fi

podman image exists "$IMAGE_SYSIMAGE:$latest" ||
	fatal "image \`$IMAGE_SYSIMAGE:$latest' not found"

tree="$(readlink -ev "$COPY_TREE")"
[ -d "$tree" ] ||
	fatal "COPY_TREE is not a directory"

workdir="${tree%/*}"
subdir="${tree##*/}"

podman image build --squash --force-rm "${podman_common_volumes[@]}" \
        -t "$IMAGE_SYSIMAGE:$tag" \
        -f - "$workdir" <<-EOF
FROM $IMAGE_SYSIMAGE:$latest
COPY "./$subdir/" /
EOF

podman image tag "$IMAGE_SYSIMAGE:$tag" "$IMAGE_SYSIMAGE:$latest"

find "$HOSTDIR" -mindepth 1 -maxdepth 1 -exec rm -rf -- '{}' '+'
