#!/bin/bash -efu

[ ! -f "$HOMEDIR/storage.conf" ] ||
	exit 0

mkdir $verbose -p -- \
	  "$HOMEDIR/cache"                          \
	  "$HOMEDIR/config"                         \
	  "$HOMEDIR/local/runtime"                  \
	  "$HOMEDIR/local/share/containers/storage" \
	  "$HOMEDIR/tmp"                            \
#

cat >"$HOMEDIR/storage.conf" <<EOF
[storage]
driver = "vfs"
runroot               = "$HOMEDIR/local/runtime"
graphroot             = "$HOMEDIR/local/share/containers/storage"
rootless_storage_path = "$HOMEDIR/local/share/containers/storage"

[storage.options]
additionalimagestores = [
]

[storage.options.vfs]
ignore_chown_errors = "false"
EOF

cat >"$HOMEDIR/env"<<EOF
export HOME="$HOMEDIR"
export TMPDIR="$HOMEDIR/tmp"
export CONTAINERS_STORAGE_CONF="$HOMEDIR/storage.conf"
export XDG_CACHE_HOME="$HOMEDIR/cache"
export XDG_CONFIG_HOME="$HOMEDIR/config"
export XDG_DATA_HOME="$HOMEDIR/local/share"
EOF
