#!/bin/bash -efu
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2023  Alexey Gladkov <gladkov.alexey@gmail.com>

. "$HOMEDIR"/env
. "$TOOLSDIR"/sh-functions

IMAGE_PACKAGES="${IMAGE_PACKAGES:?IMAGE_PACKAGES variable required}"

tag="${SYSIMAGE_TAG_PREFIX:+$SYSIMAGE_TAG_PREFIX-}$PROG"
latest="${SYSIMAGE_TAG_PREFIX:+$SYSIMAGE_TAG_PREFIX-}latest"

if podman image exists "$IMAGE_BASEIMAGE:latest"; then
	podman image tag "$IMAGE_BASEIMAGE:latest" "$IMAGE_SYSIMAGE:$tag"
	podman image tag "$IMAGE_SYSIMAGE:$tag" "$IMAGE_SYSIMAGE:$latest"
fi

! podman image exists "$IMAGE_SYSIMAGE:$tag" ||
	exit 0

copy_verndor_tools

create_vendor_helper "$PROG"
set --

if [ -n "${IMAGE_PREFILES-}" ]; then
	[ -d "${IMAGE_PREFILES-}" ] ||
		fatal "IMAGE_PREFILES must be a directory"
	set -- -v "$IMAGE_PREFILES":/.host/prefiles:z
fi

podman container run $BASE_VOLUMES "$@" \
	"$IMAGE_INSTRUMENTAL" "/.host/$PROG.chrooted"

podman image import "$HOSTDIR/image.tar" "$IMAGE_SYSIMAGE:$tag"
podman image tag "$IMAGE_SYSIMAGE:$tag" "$IMAGE_SYSIMAGE:$latest"

find "$HOSTDIR" -mindepth 1 -maxdepth 1 -exec rm -rf -- '{}' '+'
