#!/bin/bash -efu
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2023  Alexey Gladkov <gladkov.alexey@gmail.com>

. "$HOMEDIR"/env
. "$TOOLSDIR"/sh-functions

IMAGE_PACKAGES="${IMAGE_PACKAGES:?IMAGE_PACKAGES variable required}"

tag="$PROG"

! podman image exists "$IMAGE_SYSIMAGE:$tag" ||
	exit 0

create_vendor_helper "$PROG"

volumes=()
volumes+=( -v "$HOSTDIR":/.host:z )
volumes+=( -v "$CACHEDIR":/.host/cache:z )

if [ -n "${IMAGE_PREFILES-}" ]; then
	[ -d "${IMAGE_PREFILES-}" ] ||
		fatal "IMAGE_PREFILES must be a directory"
	volumes+=( -v "$IMAGE_PREFILES":/.host/prefiles:z )
fi

podman container run "${volumes[@]}" "$IMAGE_BASEIMAGE" "/.host/$PROG.chrooted"

podman image import "$HOSTDIR/image.tar" "$IMAGE_SYSIMAGE:$tag"
podman image tag "$IMAGE_SYSIMAGE:$tag" "$IMAGE_SYSIMAGE:latest"

find "$HOSTDIR" -mindepth 1 -maxdepth 1 -exec rm -rf -- '{}' '+'
