#!/bin/bash -efu
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2024  Alexey Gladkov <gladkov.alexey@gmail.com>

. "$HOMEDIR"/env

podman images --format '{{.ID}}\t{{.Size}}\t{{.Created}}\t{{.Repository}}:{{.Tag}}' |
	sort --field-separator=$'\t' -k 4,4 |
	column --table --separator=$'\t' --table-columns="IMAGE ID,SIZE,CREATED,REPOSITORY:TAG"
