#!/bin/bash -efu
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2023  Alexey Gladkov <gladkov.alexey@gmail.com>

. "$HOMEDIR"/env
. "$TOOLSDIR"/sh-functions

[ -n "$IMAGEFILE" ] ||
	fatal "IMAGEFILE variable required"

podman image exists "$IMAGE_SYSIMAGE:latest" ||
	fatal "image \`$IMAGE_SYSIMAGE:latest' not found"

verbose "exporting image \`$IMAGE_SYSIMAGE:latest' ..."

podman container create --quiet --name image "$IMAGE_SYSIMAGE:latest" / >/dev/null

podman export image |
	tar -f- --delete .host |
	${COMPRESS:-cat} > "$OUTDIR/$IMAGENAME"

podman container rm -f image >/dev/null
