#!/bin/bash -efu

. "$HOMEDIR"/env
. "$TOOLSDIR"/sh-functions

[ -n "$IMAGEFILE" ] ||
	fatal "IMAGEFILE variable required"

podman image exists "$IMAGE_SYSIMAGE" ||
	fatal "image \`$IMAGE_SYSIMAGE' not found"

verbose "exporting image \`$IMAGE_SYSIMAGE' ..."

podman container create --quiet --name image "$IMAGE_SYSIMAGE" / >/dev/null

podman export image |
	tar -f- --delete .host |
	{
		case "${COMPRESS:-raw}" in
			zstd) zstd -19 -T0 ;;
			gzip) gzip -9 ;;
			raw)  cat ;;
		esac
	} > "$IMAGEFILE"

podman container rm -f image >/dev/null

exit
