#!/bin/bash -efu

export CONTAINERS_STORAGE_CONF="$WORKDIR/storage.conf"
export HOME="$HOMEDIR"
export TMPDIR="$TEMPDIR"
export XDG_CACHE_HOME="$HOMEDIR/cache"
export XDG_CONFIG_HOME="$HOMEDIR/config"
export XDG_DATA_HOME="$HOMEDIR/local/share"

exec podman "$@"
