#!/bin/bash -efu

. "$TOOLSDIR"/sh-functions

name="$1"; shift

exec >"$HOSTDIR/run.sh"
chmod 755 "$HOSTDIR/run.sh"

printf '%s\n' \
	'#!/bin/bash' \
	''
for envname in ${CHROOTABLE_VARIABLES-}; do
	eval "envval=\"\${$envname-}\""
	quote_shell_variable envval "$envval"
	printf 'export %s="%s"\n' "$envname" "$envval"
done

printf '%s\n' \
	'' \
	'export LC_ALL=C' \
	'export LANG=C' \
	'export LANGUAGE=C' \
	'' \
	'PROG="${0##*/}"' \
	''

cat "$VENDORDIR/$VENDOR/chrooted-$name"
