#!/bin/bash -eu

IMAGE_SCRIPTDIR="${IMAGE_SCRIPTDIR:?IMAGE_SCRIPTDIR required}"

. "$HOMEDIR"/env
. "$TOOLSDIR"/sh-functions

tag="$PROG"

! podman image exists "$IMAGE_SYSIMAGE:$tag" ||
	exit 0

podman image exists "$IMAGE_SYSIMAGE:latest" ||
	fatal "image \`$IMAGE_SYSIMAGE:latest' not found"

mkdir -p -- "$HOSTDIR"/scripts.d

for script in "$IMAGE_SCRIPTDIR"/*; do
	[ -x "$script" ] ||
		continue

	case "$script" in
		*~|*.bak|*.rpmnew|*.rpmsave) continue ;;
		*) ;;
	esac

	cp $verbose -af -- "$script" "$HOSTDIR"/scripts.d/
done

print_environ()
{
	print_environ_names | sort |
	while read -r envname; do
		case "$envname" in
			INFO_*) ;;
			*) continue ;;
		esac

		envval=
		eval "envval=\"\$$envname\""
		quote_shell_variable envval "$envval"

		verbose "export $envname=\"$envval\""
		printf 'export %s="%s"\n' "$envname" "$envval"
	done
}

mkexec "$HOSTDIR/$PROG.chrooted" <<EOF
#!/bin/sh -eu
`print_environ`
for script in /.host/scripts.d/*; do
	[ -x "\$script" ] || continue
	[ -z "$verbose" ] || echo "$PROG: executing \$script ..."
	"\$script"
done
EOF

podman image build \
        -v "$HOSTDIR":/.host:z \
        -t "$IMAGE_SYSIMAGE:$tag" \
        -f - <<-EOF
FROM $IMAGE_SYSIMAGE:latest
RUN /.host/$PROG.chrooted
EOF

podman image tag "$IMAGE_SYSIMAGE:$tag" "$IMAGE_SYSIMAGE:latest"

find "$HOSTDIR" -mindepth 1 -maxdepth 1 -exec rm -rf -- '{}' '+'
